In [5]:
import pandas as pd
import numpy as np

# Explorar datos

In [6]:
df = pd.read_csv('../../Marketingcampaigns.csv')
df.head()

Customer id  Age  Gender  Location  Email Opened  Email Clicked  \
0            1   22       0     Perth             1              1   
1            2   55       0  Auckland             1              0   
2            3   15       1    Sydney             0              1   
3            4   25       0  Brisbane             1              1   
4            5   36       1  Brisbane             0              1   

   Product page visit  Discount offered  Purchased  
0                   3                 1          1  
1                   0                 0          0  
2                   2                 1          1  
3                   5                 1          0  
4                   1                 1          0

In [18]:
for col in list(df.columns):
    print(col)
    print(df[col].unique())
    print('-'*60)

Customer id
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
------------------------------------------------------------
Age
[22 55 15 25 36 30 28 19 59 45 43 37 39 18 60 53 23 62 41]
------------------------------------------------------------
Gender
[0 1]
------------------------------------------------------------
Location
['Perth' 'Auckland' 'Sydney' 'Brisbane']
------------------------------------------------------------
Email Opened
[1 0]
------------------------------------------------------------
Email Clicked
[1 0]
------------------------------------------------------------
Product page visit
[3 0 2 5 1 4]
------------------------------------------------------------
Discount offered
[1 0]
------------------------------------------------------------
Purchased
[1 0]
------------------------------------------------------------


In [16]:
df.shape

(20, 9)